[package]
name = "pg2sqlx"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.9.34-deprecated"
clap = { version = "4.5.47", features = ["derive"] }
